apiVersion: v1
kind: Secret
metadata:
  name: order-postgres-secret
  namespace: ofp
type: Opaque
stringData:
  username: postgres
  password: postgres

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-postgres-pvc
  namespace: ofp
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-postgres
  namespace: ofp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-postgres
  template:
    metadata:
      labels:
        app: order-postgres
    spec:
      containers:
        - name: order-postgres
          image: postgres:16
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
          - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: order_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: order-postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-postgres-secret
                  key: password
          volumeMounts:
            - name: order-postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: order-postgres-storage
          persistentVolumeClaim:
            claimName: order-postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: order-postgres
  namespace: ofp
spec:
  selector:
    app: order-postgres
  ports:
  - port: 5432
    targetPort: 5432

