apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: ofp
data:
  application.yml: |
    spring:
      cloud:
        gateway:
          server:
            webmvc:
              routes:
                - id: order-service
                  uri: http://order-service:8081
                  predicates:
                    - Path=/api/v1/orders/**
                - id: inventory-service
                  uri: http://inventory-service:8082
                  predicates:
                    - Path=/api/v1/products/**
                - id: payment-service
                  uri: http://payment-service:8083
                  predicates:
                    - Path=/api/v1/payments/**

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ofp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /app/config
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: config
          configMap:
            name: api-gateway-config

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: ofp
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort