apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: ofp
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://order-postgres:5432/order_db
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ofp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: order-service-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: order-postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-postgres-secret
                  key: password
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ofp
spec:
  selector:
    app: order-service
  ports:
    - port: 8081
      targetPort: 8081